<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\RegistrationNotifySubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/RegistrationNotifySubscriber.php';

return $this->privates['App\EventSubscriber\RegistrationNotifySubscriber'] = new \App\EventSubscriber\RegistrationNotifySubscriber(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), 'g.ponty@dev-web.io');
