<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGu3Erpu\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGu3Erpu/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGu3Erpu.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGu3Erpu\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerGu3Erpu\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Gu3Erpu',
    'container.build_id' => '19ad913b',
    'container.build_time' => 1529929932,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerGu3Erpu');
